### ISSUE TITLE
add dwell time

### ISSUE THREAD

**Issue by 6a68** [mozilla/chronicle#360]
@nchapman am I missing any big chunks here?

- [ ] measure dwell time in addon
  - if possible, use a worker or context outside the page to xhr down this data, rather than race against the `onbeforeunload` event
  - possibly relevant: recent (oct 2014) yahoo labs paper on measuring dwell time, including normalizing across different browsing contexts
    - http://labs.yahoo.com/news/the-science-of-personalization-goes-beyond-clicks/
    - http://labs.yahoo.com/publication/beyond-clicks-dwell-time-for-personalization/
- [ ] add dwell time to visits api (write and read)
- [ ] add dwell time to visits table in postgres
- [ ] use dwell time in search relevance calculation
  - how do we correlate dwell time with a page vs a visit? simple aggregation across all visits? or, closer to a 'nearly now' view, use the largest dwell time from visits to that page in the past week?
  - this decision impacts db task
- [ ] use dwell time in front-end visual hierarchy
  - de-emphasize or possibly hide visits with nearly-zero dwell time (except search pages)
  - use dwell time as a significant boost factor for calculating interestingness, i.e., view item size within feed
